### ISSUE TITLE
Project developed using the dataset

### ISSUE THREAD

**Issue by sayakpaul** [gulvarol/grocerydataset#5]
Hi @gulvarol.

I developed [this repository](https://github.com/sayakpaul/Grocery-Product-Detection) demonstrating training an object detection model with this dataset. My hope is that it would make it easier for folks to get started with the dataset (my repository has an EDA notebook as well), train a parameter-efficient model (I used MobileDet), and so on. 

I wanted to know if you would be up for mentioning it from the repository.

**Comment by gulvarol** [comment]
Thanks! Sure, I have added a link to the readme.

**Comment by sayakpaul** [comment]
Thank you!
